const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",
  sessionName:process.env.SESSION_ID || "SUHAIL_16_22_09_21_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTUyLFxuICAgICAgICAxODYsXG4gICAgICAgIDYxLFxuICAgICAgICAxODUsXG4gICAgICAgIDc4LFxuICAgICAgICAxNTEsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTY5LFxuICAgICAgICAyMixcbiAgICAgICAgMjIxLFxuICAgICAgICA3MSxcbiAgICAgICAgMjEwLFxuICAgICAgICAyMTIsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTYzLFxuICAgICAgICAxMzYsXG4gICAgICAgIDE1NixcbiAgICAgICAgOTIsXG4gICAgICAgIDU2LFxuICAgICAgICAxMzIsXG4gICAgICAgIDE5NSxcbiAgICAgICAgNjksXG4gICAgICAgIDk1LFxuICAgICAgICA4OSxcbiAgICAgICAgNyxcbiAgICAgICAgMTMzLFxuICAgICAgICA2OSxcbiAgICAgICAgMTY2LFxuICAgICAgICAzLFxuICAgICAgICA4NCxcbiAgICAgICAgOCxcbiAgICAgICAgOTBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDYsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMjU1LFxuICAgICAgICA5OSxcbiAgICAgICAgMTIsXG4gICAgICAgIDIyOCxcbiAgICAgICAgMTY1LFxuICAgICAgICAzMixcbiAgICAgICAgMTEwLFxuICAgICAgICAxMzgsXG4gICAgICAgIDUsXG4gICAgICAgIDc4LFxuICAgICAgICA5LFxuICAgICAgICAxOTEsXG4gICAgICAgIDM5LFxuICAgICAgICAxMDgsXG4gICAgICAgIDE2NixcbiAgICAgICAgODksXG4gICAgICAgIDE0NixcbiAgICAgICAgMTAzLFxuICAgICAgICAyNDgsXG4gICAgICAgIDksXG4gICAgICAgIDI2LFxuICAgICAgICAxNTIsXG4gICAgICAgIDYyLFxuICAgICAgICAxODcsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMTg2LFxuICAgICAgICA4NCxcbiAgICAgICAgNTAsXG4gICAgICAgIDM5LFxuICAgICAgICAzMlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTUyLFxuICAgICAgICAxMDcsXG4gICAgICAgIDI2LFxuICAgICAgICAxODEsXG4gICAgICAgIDE3NixcbiAgICAgICAgMzQsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMTQ3LFxuICAgICAgICA2OCxcbiAgICAgICAgMTc4LFxuICAgICAgICAxNjIsXG4gICAgICAgIDExNixcbiAgICAgICAgMjUsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMjAxLFxuICAgICAgICAxMzMsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTY0LFxuICAgICAgICAyNDEsXG4gICAgICAgIDQ1LFxuICAgICAgICAxOTAsXG4gICAgICAgIDU2LFxuICAgICAgICA5OSxcbiAgICAgICAgMTMyLFxuICAgICAgICAxMzMsXG4gICAgICAgIDI0NCxcbiAgICAgICAgODgsXG4gICAgICAgIDc2LFxuICAgICAgICAxNTcsXG4gICAgICAgIDI4LFxuICAgICAgICA4MCxcbiAgICAgICAgODdcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNTksXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTg0LFxuICAgICAgICAxMzYsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMjE0LFxuICAgICAgICAxODEsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTg1LFxuICAgICAgICAyMCxcbiAgICAgICAgMTY4LFxuICAgICAgICAyMDcsXG4gICAgICAgIDIwNixcbiAgICAgICAgMjQzLFxuICAgICAgICAxODQsXG4gICAgICAgIDIxMixcbiAgICAgICAgNDMsXG4gICAgICAgIDQwLFxuICAgICAgICA3MixcbiAgICAgICAgNTYsXG4gICAgICAgIDMwLFxuICAgICAgICAxNDYsXG4gICAgICAgIDE2LFxuICAgICAgICA1MSxcbiAgICAgICAgMTUzLFxuICAgICAgICAxMDUsXG4gICAgICAgIDUsXG4gICAgICAgIDUxLFxuICAgICAgICA1LFxuICAgICAgICAyMTMsXG4gICAgICAgIDUwLFxuICAgICAgICA5MlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjAwLFxuICAgICAgICAyNDcsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTIzLFxuICAgICAgICAxMTgsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMTUyLFxuICAgICAgICAxMzYsXG4gICAgICAgIDU1LFxuICAgICAgICAyNDksXG4gICAgICAgIDExNCxcbiAgICAgICAgMjI5LFxuICAgICAgICAyMjksXG4gICAgICAgIDE3MyxcbiAgICAgICAgMzEsXG4gICAgICAgIDExMyxcbiAgICAgICAgNzQsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTAxLFxuICAgICAgICA1MSxcbiAgICAgICAgMTg1LFxuICAgICAgICAyMyxcbiAgICAgICAgMTE4LFxuICAgICAgICA0OCxcbiAgICAgICAgMjEsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMTkzLFxuICAgICAgICAxNDMsXG4gICAgICAgIDEwOSxcbiAgICAgICAgNzcsXG4gICAgICAgIDIzMyxcbiAgICAgICAgNjdcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTU4LFxuICAgICAgICAxOTMsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjIyLFxuICAgICAgICAxNTksXG4gICAgICAgIDEyNyxcbiAgICAgICAgMTMyLFxuICAgICAgICAxNTYsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTExLFxuICAgICAgICAxOTYsXG4gICAgICAgIDI5LFxuICAgICAgICAxMzEsXG4gICAgICAgIDE1LFxuICAgICAgICAxMjUsXG4gICAgICAgIDI2LFxuICAgICAgICAxNjgsXG4gICAgICAgIDgwLFxuICAgICAgICAxNTEsXG4gICAgICAgIDE1LFxuICAgICAgICAyMTAsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTk5LFxuICAgICAgICA1MyxcbiAgICAgICAgMjQ1LFxuICAgICAgICAxMTMsXG4gICAgICAgIDIxNyxcbiAgICAgICAgNjUsXG4gICAgICAgIDI1MixcbiAgICAgICAgMjM1LFxuICAgICAgICAxNzYsXG4gICAgICAgIDQ3XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDEwNCxcbiAgICAgICAgICA0OCxcbiAgICAgICAgICA2NSxcbiAgICAgICAgICAyMTMsXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDEzNyxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICA3NyxcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgMTc4LFxuICAgICAgICAgIDIzNyxcbiAgICAgICAgICA0NixcbiAgICAgICAgICA5MCxcbiAgICAgICAgICA5NSxcbiAgICAgICAgICAxNzAsXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgMTQwLFxuICAgICAgICAgIDE0MixcbiAgICAgICAgICAxNzAsXG4gICAgICAgICAgMzgsXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICAxMzMsXG4gICAgICAgICAgOTAsXG4gICAgICAgICAgMTk2LFxuICAgICAgICAgIDE3MyxcbiAgICAgICAgICAxMyxcbiAgICAgICAgICAyMTgsXG4gICAgICAgICAgMTQ4LFxuICAgICAgICAgIDEwMyxcbiAgICAgICAgICAxODMsXG4gICAgICAgICAgMTA0XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDExOCxcbiAgICAgICAgICA2NixcbiAgICAgICAgICAyNTMsXG4gICAgICAgICAgMTU4LFxuICAgICAgICAgIDAsXG4gICAgICAgICAgMTQ4LFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICAyMjYsXG4gICAgICAgICAgMTY2LFxuICAgICAgICAgIDIwLFxuICAgICAgICAgIDE3LFxuICAgICAgICAgIDczLFxuICAgICAgICAgIDE4MyxcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgMjUzLFxuICAgICAgICAgIDEwMixcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgMTc1LFxuICAgICAgICAgIDE5NSxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgNDksXG4gICAgICAgICAgOTAsXG4gICAgICAgICAgODIsXG4gICAgICAgICAgODUsXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgMTQsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgMTE3LFxuICAgICAgICAgIDIzMyxcbiAgICAgICAgICA2MSxcbiAgICAgICAgICAxMDNcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA0OSxcbiAgICAgICAgMzAsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjA1LFxuICAgICAgICA4LFxuICAgICAgICA0MSxcbiAgICAgICAgMTU2LFxuICAgICAgICAyMTEsXG4gICAgICAgIDk3LFxuICAgICAgICA2OSxcbiAgICAgICAgMjExLFxuICAgICAgICAyNTEsXG4gICAgICAgIDE5NyxcbiAgICAgICAgNCxcbiAgICAgICAgNTIsXG4gICAgICAgIDE1MyxcbiAgICAgICAgOTksXG4gICAgICAgIDIwNixcbiAgICAgICAgMTA1LFxuICAgICAgICAxOTYsXG4gICAgICAgIDE2NixcbiAgICAgICAgMjUwLFxuICAgICAgICAxMDIsXG4gICAgICAgIDc3LFxuICAgICAgICAxMjgsXG4gICAgICAgIDgyLFxuICAgICAgICA0MCxcbiAgICAgICAgNDAsXG4gICAgICAgIDcsXG4gICAgICAgIDExNixcbiAgICAgICAgMjEyLFxuICAgICAgICAxOTUsXG4gICAgICAgIDIyMSxcbiAgICAgICAgOTksXG4gICAgICAgIDExNSxcbiAgICAgICAgMjUzLFxuICAgICAgICA3NSxcbiAgICAgICAgMTkxLFxuICAgICAgICAxMTgsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMTU4LFxuICAgICAgICAyMzgsXG4gICAgICAgIDE5MCxcbiAgICAgICAgOTAsXG4gICAgICAgIDU3LFxuICAgICAgICAyMTMsXG4gICAgICAgIDQ4LFxuICAgICAgICAxNDIsXG4gICAgICAgIDQ1LFxuICAgICAgICA3MSxcbiAgICAgICAgMTQ3LFxuICAgICAgICAxNDIsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMjM5LFxuICAgICAgICAyMDMsXG4gICAgICAgIDEzNixcbiAgICAgICAgNzYsXG4gICAgICAgIDkzLFxuICAgICAgICAyMDYsXG4gICAgICAgIDQyLFxuICAgICAgICAyMzcsXG4gICAgICAgIDI3LFxuICAgICAgICAzOSxcbiAgICAgICAgMTI5XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAyMjQsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiOHJYeTlHS041RjRETVFWeitSYnR6KzlNclNwbENHYk9qNXA1SzZHTHNraz1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzQ5MDY4MzQyMjMxQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI3NTFCMjFCNDExRDYzOTY3RTkwMjQ4MTRGNjBBOTRERlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjY5MzU3NjNcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiZU5qa2NpMjJSaHVkYWt6RXg2T3VvZ1wiLFxuICBcInBob25lSWRcIjogXCI3MGM5NDdiNy1lODc3LTQxOWMtOTU5YS0yM2Y2MDQ3ZmQxNmNcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTU2LFxuICAgICAgMTUyLFxuICAgICAgMjQxLFxuICAgICAgNTcsXG4gICAgICAxMDksXG4gICAgICA4MSxcbiAgICAgIDIyNyxcbiAgICAgIDM4LFxuICAgICAgMTgwLFxuICAgICAgODYsXG4gICAgICA2NixcbiAgICAgIDEsXG4gICAgICAyNDAsXG4gICAgICA2NixcbiAgICAgIDcxLFxuICAgICAgMTAsXG4gICAgICAyMTAsXG4gICAgICA3MCxcbiAgICAgIDIwOSxcbiAgICAgIDIzOFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA4NixcbiAgICAgIDkzLFxuICAgICAgMTcxLFxuICAgICAgMzcsXG4gICAgICAxMTYsXG4gICAgICAyMjEsXG4gICAgICAxOTMsXG4gICAgICAxMSxcbiAgICAgIDE2NCxcbiAgICAgIDEyMCxcbiAgICAgIDExNixcbiAgICAgIDE5NSxcbiAgICAgIDE5MSxcbiAgICAgIDI2LFxuICAgICAgODYsXG4gICAgICA2MyxcbiAgICAgIDM4LFxuICAgICAgMjMyLFxuICAgICAgMTMxLFxuICAgICAgOTNcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiWEo2Q0pTM0xcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjIzNDkwNjgzNDIyMzE6M0BzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiMTMzNjcyNjE5NDk1NjUyOjNAbGlkXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDS21ENjRRQ0VNcmx1N2NHR0FNZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJmTzh4UkZqM290VnB6VjBaWGNIOVQ1aENLMHY3UFpyUloyVkR5akpDZ2dRPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcInZRQ1pFQS8vejNnbXIzd2VLUjlodjVyOVZVMEU3T3RJbm5PMmNZL1RhRjFQNXN5Q29uWlNsL0dnNmRaMWRYQVVhVmhpU1BTaXh3ci9zd1MzRC9mTUF3PT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIlBMWmVpcE1lVVdac1ZURktaY3R2TmhGRWdZOE03VkdEMzMySmQyekIrMEN1YkQyWk9wVkh2MkhwdFNYa2pNRWd3c09mTi9FM2JFOCtUTHcyOE1Va2l3PT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjIzNDkwNjgzNDIyMzE6M0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDEyNCxcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgNDksXG4gICAgICAgICAgNjgsXG4gICAgICAgICAgODgsXG4gICAgICAgICAgMjQ3LFxuICAgICAgICAgIDE2MixcbiAgICAgICAgICAyMTMsXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDIwNSxcbiAgICAgICAgICA5MyxcbiAgICAgICAgICAyNSxcbiAgICAgICAgICA5MyxcbiAgICAgICAgICAxOTMsXG4gICAgICAgICAgMjUzLFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICA2NixcbiAgICAgICAgICA0MyxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAyNTEsXG4gICAgICAgICAgNjEsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICAxMDMsXG4gICAgICAgICAgMTAxLFxuICAgICAgICAgIDY3LFxuICAgICAgICAgIDIwMixcbiAgICAgICAgICA1MCxcbiAgICAgICAgICA2NixcbiAgICAgICAgICAxMzAsXG4gICAgICAgICAgNFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI2OTM1NzU4LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBSXVDXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFJdUMuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJCY2hCZkFvK3pPYXdMdFA5MXpZM1c3aktNRGFnMlRxeUY2dFd0MFVzOEtzPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjU0NzAxMzAzMyxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzI1NDY0Mjk4NzUxXCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
